# Generated by Django 5.2.15 on 2026-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_role_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='daily_report_opt_in',
            field=models.BooleanField(default=True, help_text='Send a daily progress report to the guardian.'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, default='', help_text='Guardian WhatsApp number in international format, e.g. 919876543210', max_length=20),
        ),
    ]
