# Generated by Django 5.2.15 on 2026-07-03 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0003_alter_scenario_model_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=50)),
                ('variant_label', models.CharField(blank=True, max_length=100)),
                ('student_prompt', models.TextField(blank=True)),
                ('generated_code', models.TextField(blank=True)),
                ('stdout_log', models.TextField(blank=True)),
                ('stderr_log', models.TextField(blank=True)),
                ('stage_images', models.JSONField(default=list, help_text='List of base64-encoded stage images')),
                ('output_image', models.TextField(blank=True)),
                ('prediction', models.TextField(blank=True, help_text='Final prediction text/JSON')),
                ('explanation', models.TextField(blank=True)),
                ('data_source', models.CharField(choices=[('PRELOADED', 'Pre-loaded sample image'), ('DRAWN', 'Student-drawn canvas input'), ('UPLOAD', 'Student-uploaded image')], default='DRAWN', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_experiments', to='scenarios.scenario')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_experiments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
