# Generated by Django 5.2.15 on 2026-07-10 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0003_alter_scenario_model_type'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('quiz', 'Quiz (auto-graded)'), ('task', 'Task (LLM-graded)'), ('submission', 'Submission (LLM-graded)')], default='quiz', max_length=16)),
                ('module_key', models.CharField(db_index=True, max_length=40)),
                ('target_grade', models.IntegerField(blank=True, help_text='CBSE class; blank = any', null=True)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('rubric', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=100)),
                ('is_template', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('linked_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='scenarios.scenario')),
                ('school', models.ForeignKey(blank=True, help_text='Blank = global Sutra template available to all schools', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='schools.school')),
            ],
            options={
                'ordering': ['module_key', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to remove from the student dashboard')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('submitted', 'Submitted'), ('graded', 'Graded')], db_index=True, default='assigned', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_students', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=list, help_text='Selected option indices for a quiz')),
                ('content', models.TextField(blank=True, help_text='Free-text answer for a task/submission')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('is_auto_graded', models.BooleanField(default=False)),
                ('llm_feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending grade'), ('grading', 'Grading…'), ('graded', 'Graded')], db_index=True, default='pending', max_length=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.studentassignment')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
