import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5180,

    // DO NOT WATCH THE BUILD ARTEFACTS. This is not a tidiness preference --
    // without it the dev server stops answering requests entirely.
    //
    // `public/` holds ~415 MB once all five domains are built: 302 MB of
    // embedding vectors, the 98 MB ONNX, 11 MB of WebAssembly, plus a few
    // hundred preview JPEGs. Vite watches publicDir by default, and this
    // project sits inside a OneDrive-synced folder where every stat call goes
    // through a sync filter. Chokidar's recursive walk over that never
    // finishes, and because it blocks the same event loop that serves HTTP,
    // the symptom is not "slow file watching" -- it is a server that reports
    // "ready in 1081ms" and then times out on a 4 KB favicon.
    //
    // None of these ever need hot-reload: they are generated by the Python
    // pipeline and read once per page load.
    watch: {
      ignored: [
        '**/public/embeddings/**',
        '**/public/models/**',
        '**/public/ort/**',
        '**/public/heads/**',
        '**/public/parity/**',
        '**/datasets/**',
        '**/dist/**',
        '**/.cache/**',
      ],
    },
  },

  // onnxruntime-web ships prebuilt ESM that Vite's dep optimiser mangles --
  // it rewrites the relative import of the sibling .mjs WASM loader, which then
  // 404s at session-creation time with an error that reads like a missing
  // model. Excluding it leaves the package alone; the actual .wasm is served
  // from public/ort/ (see scripts/copy_ort.mjs).
  optimizeDeps: { exclude: ['onnxruntime-web', 'onnxruntime-web/wasm'] },

  // The .wasm in public/ is 11 MB. Vite warns about large assets at 500 KB,
  // which is useful for our own code and pure noise for a runtime binary.
  build: { chunkSizeWarningLimit: 1200 },

  // The CSS here is plain -- no PostCSS pipeline. Pin an empty config so Vite
  // stops searching upwards and picking up the unrelated Tailwind
  // postcss.config.mjs that lives in the parent Downloads folder.
  css: { postcss: {} },
});
