# Generated by Django 5.2.15 on 2026-07-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_alter_datavariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='model_type',
            field=models.CharField(choices=[('REGRESSION', 'Linear Regression'), ('CLASSIFICATION', 'Classification'), ('NEURAL_NETWORK', 'Neural Network'), ('COMPUTER_VISION', 'Computer Vision')], db_index=True, max_length=20),
        ),
    ]
