# Generated by Django 5.2.15 on 2026-07-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_alter_scenario_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavariant',
            name='watch_for',
            field=models.TextField(blank=True, default='', help_text='What this variant will do to the model — shown at data review.'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='data_story',
            field=models.TextField(blank=True, default='', help_text='How and why this data was collected.'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='grade_band',
            field=models.CharField(blank=True, default='6-8', max_length=10),
        ),
        migrations.AddField(
            model_name='scenario',
            name='guide_steps',
            field=models.JSONField(blank=True, default=list, help_text='Ordered student instructions rendered as a checklist (guided flows).'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='outcome_guide',
            field=models.TextField(blank=True, default='', help_text='What to look for in the results — shown beside the LLM explanation.'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='story',
            field=models.TextField(blank=True, default='', help_text='Why would anyone want to predict this? Shown before training.'),
        ),
    ]
